name: Delivery
on:
  push:
    branches:
      - 'code'
      - '!master'

jobs:
  Deploy:
    runs-on: ubuntu-18.04

    container:
      image: gophertips/ci:2

    steps:
      - name: Download the source code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Fetch master branch
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master

      - name: Build the static files
        run: |
          git worktree add public master
          cd public
          ls -A | grep -E -v '^(CNAME|\.git)$' | xargs rm -rf
          cd ..
          hugo

      - name: Commit static files
        env:
          GITHUB_TOKEN: ${{ secrets.GIT }}
        run: |
          cd public
          if [ "$(git diff | wc -l)" -ne "0" ]; then
            git config user.name "GitHub Actions"
            git config user.email "github-actions@users.noreply.github.com"
            git commit -am "Updated at '$(date -u +"%Y-%m-%d %T")'"
            git push
          fi
